# -*- coding: utf-8 -*-
"""THE4.ipynb adlı not defterinin kopyası

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nA-TGT1KaLOKNfJoHpNFBA3w2-qseqn8
"""

# IMPLEMENT YOUR FUNCTIONS IN THIS CODE CELL OR
# IN THE PREVIOUS CODE CELL(S) THAT YOU MAY WANT TO CREATE
# Selim Gul 29200
def show_remaining(productDict):
    condition = bool(productDict)
    if condition:
      sortedProducts=sorted(productDict.keys(), key=lambda x:x.lower())
      for product in sortedProducts:
          print(product, ":", productDict[product])
    else:
      print("Inventory is empty!")


def sell_product(productDict):
    userInput = input("Please enter products to sell: ")
    info = userInput.split("\n")
    meal = info[0]
    meal = meal.strip()
    meal = meal.strip(" \n\t.,;:!?\n#()[]{}&/+_-*'\"=@")
    mealList = list(meal.split("-"))
    meals = info[0].split("-")
    for meal in meals:
        meal = meal.lower()
        key, value = meal.split("_")
        value = int(value)
        if key in productDict:
            if value <= productDict[key]:
                productDict[key] -= value
                print(value, key, "sold.")
                if productDict[key] == 0:
                    productDict.pop(key)
            else:
                print("There is not enough", key, "in inventory.")
        else:
            print(key, "does not exist in inventory.")


def import_inventory():

    inFile = open("products.txt", "r")
    lineList = inFile.readlines()
    inFile.close()
    productDict = {}
    for line in lineList:
        info = line.split("\n")
        meal = info[0]
        meal = meal.strip()
        meal = meal.strip(" \n\t.,;:!?\n#()[]{}&/+_-*'\"=@")
        mealList = list(meal.split("-"))
        meals = info[0].split("-")
        for meal in meals:
            meal = meal.lower()
            key, value = meal.split("_")
            value = int(value)
            if key not in productDict:
                productDict[key] = value
            else:
                productDict[key] += value
    return productDict

# DO NOT MODIFY THIS CODE CELL, JUST RUN IT

products = import_inventory()
decision = ""
while decision != "3":
  print("*---------------------------")
  print("[1] Sell products")
  print("[2] Show remaining inventory")
  print("[3] Terminate")

  decision = input("Please enter your decision: ")
  print("____________________________")
  if decision == "1":
    sell_product(products)
  elif decision == "2":
    show_remaining(products)
  elif decision == "3":
    print("Terminating...")
  else:
    print("Invalid input!")