# -*- coding: utf-8 -*-
"""selimgul_q5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IDCsb9NmaWuQmYL6vPzSIddqwb1PU5cy
"""

nums = [9,7,11,1,2,8,2,5]
target = 10

def targetFinder(nums, target):
  while nums != []:   
    for i in range(len(nums)):
      for j in range(i,len(nums)):
          if nums[i] + nums[j] == target:
            print((i, j))

targetFinder(nums, target)