# -*- coding: utf-8 -*-
"""selimgul_q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17md7UM9m6Dajiy2ynIOZ5Ns17l25LzSl
"""

credits = int(input("Please enter the number of credits earned: "))
if credits < 30:
  print("Freshman")
if credits >= 30 and credits < 60:
  print("Sophomore")
if credits >= 60 and credits < 90:
  print("Junior")
if credits >= 90:
  print("Senior")