# -*- coding: utf-8 -*-
"""selimgul_q6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rahsgWOH3MF8mWAji-_--tgnvF5qpIjw
"""

inFile = open("vaccine.txt", "r")
lines = inFile.readlines()[1:]
user = input("Please enter your group: ")
user = user.lower()
for i in range(len(lines)):
  allStr = lines[i]
  allStr = allStr.strip("\n")
  lst1 = allStr.split(",")
  name = lst1[1]
  name = name.lower()
  if user == name:
    print("Stage", lst1[0], "Order", lst1[2])