# -*- coding: utf-8 -*-
"""selimgul_q4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U6UkCXtKHoucDyFEW35KbijJLKhP8G_a
"""

from random import *
score1 = 0
score2 = 0
for x in range(32):
  dice = randint(1,6)
  score1 += dice

for y in range(32):
  dice1 = randint(1,6)
  score2 += dice1

score1 = int(score1)
score2 = int(score2)


dif1 = 121-score1
dif2 = 121-score2

if score1 == 121:
  print("score 1: ", score1)
  print("Player 1 wins!")
elif score1 > 121:
  print("score 1: ", score1)
  print("Player 2 wins!")
elif score2 == 121:
  print("score 1: ", score1)
  print("score 2: ", score2)
  print("Player 2 wins!")
elif score2 > 121:
  print("score 1: ", score1)
  print("score 2: ", score2)
  print("Player 1 wins!")
elif score1 == score2:
  print("score 1: ", score1)
  print("score 2: ", score2)
  print("There is a tie!")
elif dif1 < dif2:
  print("score 1: ", score1)
  print("score 2: ", score2)
  print("Player 1 wins!")
elif dif2 < dif1:
  print("score 1: ", score1)
  print("score 2: ", score2)
  print("Player 2 wins!")